valor = str(input("Entre com um texto:"))
print("Classe da variável : ", type(valor))
print("Ele é um valor alphanumerico",valor.isalnum())
print("Ele é um valor alpha",valor.isalpha())
print("Ele é um valor ASCII",valor.isascii())
print("Ele é um valor digito",valor.isdigit())
print("Ele é um valor decimal",valor.isdecimal())
print("Ele é um valor espaço",valor.isspace())
print("Ele é um valor maiúsculo",valor.isupper())
